FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN addgroup app && adduser -S -G app app

RUN chown -R app:app .

USER app

RUN npm install

COPY . .

EXPOSE 5173

ENTRYPOINT [ "/usr/local/bin/npm", "run" ]

CMD [ "dev" ]